WebClient/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace WebClient.Pages
{
	[AllowAnonymous]
	[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
	[IgnoreAntiforgeryToken]
	public class ErrorModel : PageModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

		private readonly ILogger<ErrorModel> _logger;

		public ErrorModel(ILogger<ErrorModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
			RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
		}
	}
}

WebClient/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebClient.Pages
{
	[AllowAnonymous]
	public class IndexModel : PageModel
	{
		public IndexModel() { }

		public void OnGet()
		{

		}
	}
}

WebClient/Pages/Private.cshtml.cs
using ApiServices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace WebClient.Pages
{

	public class PrivateModel : PageModel
	{
		private readonly IApi01Service api01Service;
		private readonly IApi02Service api02Service;

		public PrivateModel(IApi01Service api01Service, IApi02Service api02Service)
		{
			this.api01Service = api01Service;
			this.api02Service = api02Service;
		}

		public string ApiResponse { get; set; }

		public void OnGet()
		{

		}

		public async Task<ActionResult> OnGetApi01PublicAsync()
		{
			ApiResponse = await api01Service.CallPublicEndPoint();

			return Page();
		}


		public async Task<ActionResult> OnGetApi01ProtectedAsync()
		{
			var response = await api01Service.CallProtectedEndPoint();

			ApiResponse = response.Value;

			return Page();
		}

		public async Task<ActionResult> OnGetMeAsync()
		{
			var response = await api01Service.GetMe();

			ApiResponse = response.Value;

			return Page();
		}

		public async Task<ActionResult> OnGetApi02PublicAsync()
		{
			ApiResponse = await api02Service.CallPublicEndPoint();

			return Page();
		}

		public async Task<ActionResult> OnGetApi02ProtectedAsync()
		{
			var response = await api02Service.CallProtectedEndPoint();

			ApiResponse = response.Value;

			return Page();
		}
	}
}

WebClient/Pages/Index.cshtml
@page
@model IndexModel
@{
	ViewData["Title"] = "Home page";
}

<h1 class="mb-3">@ViewData["Title"]</h1>
<p>This page is publically accessible</p>
<p>The Private page requires authentication and authorization.</p>

WebClient/Pages/Private.cshtml
@page
@model PrivateModel
@using Microsoft.AspNetCore.Authentication
@{
	ViewData["Title"] = "Private page";
}

<div class="row">
	<div class="col-12 mb-2">
		<h1>@ViewData["Title"]</h1>
		<p>This page requires authentication.</p>
		<h3>Api tests</h3>
	</div>
	<div class="col-6">
		<h5>Api 1</h5>
		<p><a asp-page-handler="Api01Public" class="btn btn-outline-secondary mr-2">Public</a> <a asp-page-handler="Api01Protected" class="btn btn-outline-secondary">Protected</a> <a asp-page-handler="Me" class="btn btn-outline-secondary">Me</a></p>
	</div>
	<div class="col-6">
		<h5>Api 2</h5>
		<p><a asp-page-handler="Api02Public" class="btn btn-outline-secondary mr-2">Public</a> <a asp-page-handler="Api02Protected" class="btn btn-outline-secondary">Protected</a></p>
	</div>
	<div class="col-12 mt-2">
		Api response: @Model.ApiResponse
	</div>
	<hr class="col-12" />
	<div class="col-12 mt-4 small">
		<h5>Claims</h5>
		<dl>
			@foreach (var claim in User.Claims)
			{
				<dt>@claim.Type</dt>
				<dd>@claim.Value</dd>
			}
		</dl>

		<h5 class="mt-2">Properties</h5>

		<dl>
			@foreach (var prop in (await AuthenticationHttpContextExtensions.AuthenticateAsync(Model.HttpContext)).Properties.Items)
			{
				<dt>@prop.Key</dt>
				<dd>@prop.Value</dd>
			}
		</dl>
	</div>
</div>

WebClient/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - WebClient</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container">
				<a class="navbar-brand" asp-area="" asp-page="/Index">WebClient</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

					@if (User.Identity.IsAuthenticated)
					{
						<ul class="navbar-nav flex-grow-1">
							<li class="nav-item">
								<span class="nav-link text-dark">Signed in as @User.Identity.Name</span>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark ml-3" asp-area="MicrosoftIdentity" asp-controller="Account" asp-action="SignOut">Sign out</a>
							</li>
						</ul>
					}

					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-page="/Private">Private</a>
						</li>
						@if (!User.Identity.IsAuthenticated)
						{
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="MicrosoftIdentity" asp-controller="Account" asp-action="SignIn">Sign in</a>
							</li>
						}
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2021 - WebClient
		</div>
	</footer>

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>

	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>